export const ERROR_CODES = {
  // Auth errors
  INVALID_CREDENTIALS: 'AUTH_001',
  TOKEN_EXPIRED: 'AUTH_002',
  TOKEN_INVALID: 'AUTH_003',
  EMAIL_NOT_VERIFIED: 'AUTH_004',
  ACCOUNT_LOCKED: 'AUTH_005',
  ACCOUNT_DEACTIVATED: 'AUTH_006',

  // Validation errors
  VALIDATION_FAILED: 'VAL_001',
  DUPLICATE_ENTRY: 'VAL_002',

  // Resource errors
  NOT_FOUND: 'RES_001',
  FORBIDDEN: 'RES_002',
  CONFLICT: 'RES_003',

  // Service errors
  SERVICE_UNAVAILABLE: 'SVC_001',
  TIMEOUT: 'SVC_002',
  CIRCUIT_OPEN: 'SVC_003',
} as const;
